#ifndef EMACS_AC_BREAK_H
#define EMACS_AC_BREAK_H

#define aBreak
#define bBreak
#define cBreak
#define dBreak
#define eBreak
#define fBreak
#define gBreak
#define hBreak
#define iBreak
#define jBreak
#define kBreak
#define lBreak
#define mBreak
#define nBreak
#define oBreak
#define pBreak
#define qBreak
#define rBreak
#define sBreak
#define tBreak
#define uBreak
#define vBreak
#define wBreak
#define xBreak
#define yBreak
#define zBreak
#define a_Break
#define b_Break
#define c_Break
#define d_Break
#define e_Break
#define f_Break
#define g_Break
#define h_Break
#define i_Break
#define j_Break
#define k_Break
#define l_Break
#define m_Break
#define n_Break
#define o_Break
#define p_Break
#define q_Break
#define r_Break
#define s_Break
#define t_Break
#define u_Break
#define v_Break
#define w_Break
#define x_Break
#define y_Break
#define z_Break
#define ABREAK
#define BBREAK
#define CBREAK
#define DBREAK
#define EBREAK
#define FBREAK
#define GBREAK
#define HBREAK
#define IBREAK
#define JBREAK
#define KBREAK
#define LBREAK
#define MBREAK
#define NBREAK
#define OBREAK
#define PBREAK
#define QBREAK
#define RBREAK
#define SBREAK
#define TBREAK
#define UBREAK
#define VBREAK
#define WBREAK
#define XBREAK
#define YBREAK
#define ZBREAK
#define A_BREAK
#define B_BREAK
#define C_BREAK
#define D_BREAK
#define E_BREAK
#define F_BREAK
#define G_BREAK
#define H_BREAK
#define I_BREAK
#define J_BREAK
#define K_BREAK
#define L_BREAK
#define M_BREAK
#define N_BREAK
#define O_BREAK
#define P_BREAK
#define Q_BREAK
#define R_BREAK
#define S_BREAK
#define T_BREAK
#define U_BREAK
#define V_BREAK
#define W_BREAK
#define X_BREAK
#define Y_BREAK
#define Z_BREAK


#endif /* EMACS_AC_BREAK_H */
